{
  parserClass="org.cutejs.lang.parser.CuteParser"
  parserUtilClass="org.cutejs.lang.parser.CuteParserUtil"

  elementTypeHolderClass="org.cutejs.lang.psi.CuteTypes"
  elementTypeClass="org.cutejs.lang.psi.CuteCompositeElementType"
  tokenTypeClass="org.cutejs.lang.psi.CuteTokenType"

  psiClassPrefix="JST"
  psiImplClassSuffix="Impl"
  psiPackage="org.cutejs.lang.psi"
  psiImplPackage="org.cutejs.lang.psi.impl"
}

JSTemplate ::= item_*

private item_ ::= (T_OUTER_DATA|statement|data)

data ::= T_DATA+
statement ::= expression T_CLOSE
expression ::= (escape|interpolate|typedef|namespace|export|partial|inline|eval)
escape ::= T_ESCAPE T_EVAL
interpolate ::= T_INTERPOLATE T_EVAL
typedef ::= T_TYPEDEF T_THIS_PROPERTY T_ARRAYS_PECIFIER? T_DOC_TYPE
namespace ::= T_NAMESPACE T_IDENTIFIER
export ::= T_EXPORT export_args
partial ::= T_PARTIAL include_args
inline ::= T_INLINE include_args
include_args ::= T_IDENTIFIER T_COMMA T_EVAL T_COMMA export_args
export_args ::= T_IDENTIFIER T_ARRAY_SPECIFIER?
eval ::= T_OPEN T_EVAL
